// export const __mainFrameRootPath = document.getElementById("mainFrameRootPath").value;
// export const __appletPathConfig = document.getElementById("appletPathConfig").value;
// export const __currentPersonID = document.getElementById("currentPersonID").value;
// export const __currentCompanyID = document.getElementById("currentCompanyID").value;
// export const __currentCompanyInfoID = document.getElementById("currentCompanyInfoID").value;
// export const __agentName = document.getElementById("agentName").value;
// export const __agentID = document.getElementById("agentID").value;
// export const __xtEduRootPath = document.getElementById("xtEduRootPath").value;
// export const __eduShopID = document.getElementById("eduShopID").value;
// export const __vshopPath = document.getElementById("vshopPath").value;
// export const __companyID = document.getElementById("companyID").value;
// export const __hhrHL = document.getElementById("hhrHL").value;
// export const __partnerId = document.getElementById("partnerId").value;
// export const __hlPersonID = document.getElementById("hlPersonID").value;
// export const __parentId = document.getElementById("parentId").value;
// export const __number = document.getElementById("number").value; 

export const env_hostUrl = 'http://47.93.244.206:8089/';
// export const env_hostUrl = 'http://localhost:8089/'; 
